
package webservices;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "BuscaLivroService", targetNamespace = "http://service.biblioteca/", wsdlLocation = "http://localhost:8080/services/BuscaLivro?wsdl")
public class BuscaLivroService
    extends Service
{

    private final static URL BUSCALIVROSERVICE_WSDL_LOCATION;
    private final static WebServiceException BUSCALIVROSERVICE_EXCEPTION;
    private final static QName BUSCALIVROSERVICE_QNAME = new QName("http://service.biblioteca/", "BuscaLivroService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/services/BuscaLivro?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BUSCALIVROSERVICE_WSDL_LOCATION = url;
        BUSCALIVROSERVICE_EXCEPTION = e;
    }

    public BuscaLivroService() {
        super(__getWsdlLocation(), BUSCALIVROSERVICE_QNAME);
    }

    public BuscaLivroService(WebServiceFeature... features) {
        super(__getWsdlLocation(), BUSCALIVROSERVICE_QNAME, features);
    }

    public BuscaLivroService(URL wsdlLocation) {
        super(wsdlLocation, BUSCALIVROSERVICE_QNAME);
    }

    public BuscaLivroService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BUSCALIVROSERVICE_QNAME, features);
    }

    public BuscaLivroService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BuscaLivroService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns BuscaLivro
     */
    @WebEndpoint(name = "BuscaLivroPort")
    public BuscaLivro getBuscaLivroPort() {
        return super.getPort(new QName("http://service.biblioteca/", "BuscaLivroPort"), BuscaLivro.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BuscaLivro
     */
    @WebEndpoint(name = "BuscaLivroPort")
    public BuscaLivro getBuscaLivroPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.biblioteca/", "BuscaLivroPort"), BuscaLivro.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BUSCALIVROSERVICE_EXCEPTION!= null) {
            throw BUSCALIVROSERVICE_EXCEPTION;
        }
        return BUSCALIVROSERVICE_WSDL_LOCATION;
    }

}
