
package webservices;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "BuscaLivro", targetNamespace = "http://service.biblioteca/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BuscaLivro {


    /**
     * 
     * @param arg0
     * @return
     *     returns webservices.Livro
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obter", targetNamespace = "http://service.biblioteca/", className = "webservices.Obter")
    @ResponseWrapper(localName = "obterResponse", targetNamespace = "http://service.biblioteca/", className = "webservices.ObterResponse")
    @Action(input = "http://service.biblioteca/BuscaLivro/obterRequest", output = "http://service.biblioteca/BuscaLivro/obterResponse")
    public Livro obter(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<webservices.Livro>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "buscar", targetNamespace = "http://service.biblioteca/", className = "webservices.Buscar")
    @ResponseWrapper(localName = "buscarResponse", targetNamespace = "http://service.biblioteca/", className = "webservices.BuscarResponse")
    @Action(input = "http://service.biblioteca/BuscaLivro/buscarRequest", output = "http://service.biblioteca/BuscaLivro/buscarResponse")
    public List<Livro> buscar(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
